services:
  - type: web
    name: mis-dashboard-backend
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CSV_PATH
        value: data.csv
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "https://frontend-cufrthi7r-vinnies-projects-3b4c43c2.vercel.app,https://frontend-liart-theta-skl27urjf6.vercel.app,https://frontend-rcwtt2sde-vinnies-projects-3b4c43c2.vercel.app"
