services:
  - type: web
    name: ngo-mis-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: CSV_PATH
        value: "MIS_Program(MIS_Program) (1).csv"
      - key: PYTHON_VERSION
        value: "3.14.3"
